# Generated by Django 4.0.4 on 2022-04-15 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Info',
        ),
    ]
